apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aegisheal-db-secret
  namespace: monitoring-platform
  labels:
    app.kubernetes.io/part-of: aegisheal
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: aegisheal-db-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: ai-monitoring-platform-dev/rds/master-password
        property: password
    - secretKey: DB_USER
      remoteRef:
        key: ai-monitoring-platform-dev/rds/master-password
        property: username
